[2024-08-19T08:56:25.608+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-19T08:56:25.624+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_dag.branch manual__2024-08-19T08:31:27+00:00 [queued]>
[2024-08-19T08:56:25.631+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_dag.branch manual__2024-08-19T08:31:27+00:00 [queued]>
[2024-08-19T08:56:25.632+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-19T08:56:25.648+0000] {taskinstance.py:2879} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-08-19 08:31:27+00:00
[2024-08-19T08:56:25.656+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-19T08:56:25.657+0000] {standard_task_runner.py:72} INFO - Started process 209 to run task
[2024-08-19T08:56:25.656+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'branch', 'manual__2024-08-19T08:31:27+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpsm42hvi0']
[2024-08-19T08:56:25.666+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask branch
[2024-08-19T08:56:25.711+0000] {task_command.py:467} INFO - Running <TaskInstance: xcom_dag.branch manual__2024-08-19T08:31:27+00:00 [running]> on host 70607853bfdd
[2024-08-19T08:56:25.825+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T08:31:27+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-19T08:31:27+00:00'
[2024-08-19T08:56:25.827+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-19T08:56:25.844+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-19T08:56:25.868+0000] {python.py:240} INFO - Done. Returned value was: t2
[2024-08-19T08:56:25.868+0000] {branch.py:38} INFO - Branch into t2
[2024-08-19T08:56:25.869+0000] {skipmixin.py:230} INFO - Following branch ('t2',)
[2024-08-19T08:56:25.878+0000] {skipmixin.py:278} INFO - Skipping tasks [('t3', -1)]
[2024-08-19T08:56:25.917+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-19T08:56:25.918+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=branch, run_id=manual__2024-08-19T08:31:27+00:00, execution_date=20240819T083127, start_date=20240819T085625, end_date=20240819T085625
[2024-08-19T08:56:25.965+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-19T08:56:26.009+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-19T08:56:26.011+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
